### PR TITLE
use a proper workflow scope

### PR DESCRIPTION
**Pull request by akosyakov**
there is no scope workflows, but only workflow: https://docs.github.com/en/developers/apps/building-oauth-apps/scopes-for-oauth-apps#available-scopes

### CODE REVIEW

**Review by cschleiden — APPROVED** [review]
🤦 

Awesome, thanks for catching this!

**Comment by akosyakov** [comment]
@cschleiden Would you be able to publish a new version to Open VSX? 🙏

**Comment by cschleiden** [comment]
@akosyakov I had published 0.18.0 after merging to the VS Code marketplace. Is that automatically mirrored to open vsx? Never used that before

**Comment by akosyakov** [comment]
ah I see

It would be cool if you can your namespace in Open VSX and setup the publishing process. 🙏 Docs are here: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions Technically it should be straightforward. You are basically have to get a token and call ovsx publish with it, for instance how RedHat is publishing the java extension: https://github.com/redhat-developer/vscode-java/blob/ff51dbffc30dd23190335c929e9f34ccdf511554/Jenkinsfile#L73-L82

**Pull request merged**
